project:
  type: book
  output-dir: docs

book:
  title: "Statistics for the Experimental Bench Biologist"
  author: "Jeffrey A. Walker"
  date: "9/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/setup.qmd
    - chapters/reading-writing-wrangling.qmd
    - chapters/plotting-models.qmd
    - chapters/uncertainty-sd-and-se.qmd
    - chapters/p-values.qmd
    - chapters/inference-errors.qmd
    - chapters/intro-stat-modeling.qmd
    - chapters/continuous_x.qmd
    - chapters/one-factor.qmd
    - chapters/model-checking.qmd
    - chapters/multiple-testing.qmd
    - chapters/two-factors.qmd
    - chapters/lmm.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc-depth: 4
editor: source

