project:
  type: book

book:
  title: "Statistics for the Experimental Bench Biologist"
  author: "Jeffrey A. Walker"
  date: "9/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - chapters/06-data-reading_writing.qmd
    - chapters/12-introduction-to-statistical-modeling.qmd
    - chapters/22-continuous_X.qmd
    - chapters/24-categorical_X.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
editor: visual

